#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn check-lint || {
    echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.';
    false;
}

yarn check-types || {
    echo 'Are you seriously trying to write that? Make the changes required above.';
    false;
}

yarn build || {
    echo 'Your project cannot build idiot, please fix it';
    false;
}

echo 'Yeah congratulations, your file accepted';